version: '3.3'
services:
  jupyter:
    image: jupyter/tensorflow-notebook
    build: .
    volumes:
    - ./work:/home/jovyan/work
    command: bash -c "start-notebook.sh"
    ports:
    - "8888:8888"
